// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSDwpvVemXzvBnFFJLE0o4Qi01Bk6H9gI',
    appId: '1:6586098523:android:a96bfe15b0b6f22c54b07e',
    messagingSenderId: '6586098523',
    projectId: 'najlepszapizzawmiescier',
    storageBucket: 'najlepszapizzawmiescier.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEZJ1gSelMvCXgopHWAWuYgF8ry_WRuEg',
    appId: '1:6586098523:ios:c3ae19ea005f5c8e54b07e',
    messagingSenderId: '6586098523',
    projectId: 'najlepszapizzawmiescier',
    storageBucket: 'najlepszapizzawmiescier.appspot.com',
    iosClientId: '6586098523-h13vnm3fr21u6qrub38f76q2cdcg7dli.apps.googleusercontent.com',
    iosBundleId: 'com.patrykbarszczewski.najlepszaPizzaWMiescie',
  );
}
