// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC3iMikw7YZy8csNvSMjKhj0WVQ32TZK0',
    appId: '1:236980176738:android:a9d457c68b2df88c648e3b',
    messagingSenderId: '236980176738',
    projectId: 'pizza-rybnik-999',
    storageBucket: 'pizza-rybnik-999.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOZXc9MRY2Fvb6SNh88COYub8KMJ_q1Z8',
    appId: '1:236980176738:ios:13dc1208448db937648e3b',
    messagingSenderId: '236980176738',
    projectId: 'pizza-rybnik-999',
    storageBucket: 'pizza-rybnik-999.appspot.com',
    iosClientId: '236980176738-cm1qjn7tpuqm37f9538cmgv4dafo3fpa.apps.googleusercontent.com',
    iosBundleId: 'com.patrykbarszczewski.najlepszaPizzaWMiescie',
  );
}
